spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: orchestrator-route
          uri: http://orchestrator-service:8081
          predicates:
            - Path=/api/v1/orchestrator/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty.http.client: DEBUG

server:
  port: 8082

