spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: orchestrator-route
          uri: http://orchestrator-service:8081
          predicates:
            - Path=/api/v1/orchestrator/**

server:
  port: 8082
