apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: git@github.com:tosrikant/god_orchestrator.git
      sshPrivateKeySecret:
        name: github-ssh-key
        key: ssh-privatekey
