apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: god-mode-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /api/v1/orchestrator
        pathType: Prefix
        backend:
          service:
            name: gateway-service
            port:
              number: 8082
